# Generated by Django 5.1.1 on 2024-09-20 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_profile_id'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bill',
            name='address',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('profile', 'address')},
        ),
    ]
