# Generated by Django 5.1.1 on 2024-09-20 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_profile_id'),
        ('billing', '0002_alter_bill_unique_together_bill_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='profile',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bill',
            name='date_issued',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='address',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('user', 'address')},
        ),
    ]
